03_DB/99_django_either_pjt/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eithers/', include('eithers.urls')),
]

03_DB/99_django_either_pjt/eithers/urls.py
from django.urls import path
from . import views 

app_name = 'eithers'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path(
        '<int:question_pk>/comments/', 
        views.comments_create, 
        name='comments_create'
    ),
    path('random/', views.random, name='random'),
]

03_DB/99_django_either_pjt/eithers/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=50)
    issue_a = models.CharField(max_length=50)
    issue_b = models.CharField(max_length=50)


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    pick = models.BooleanField()
    # pick = models.IntegerField()

03_DB/99_django_either_pjt/eithers/forms.py
from django import forms
from .models import Question, Comment


class QuestionForm(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = '__all__'


class CommentForm(forms.ModelForm):
    PICK_A = False
    PICK_B = True
    PICKS = [
        (PICK_A, 'BLUE'),
        (PICK_B, 'RED'),
    ]
    pick = forms.ChoiceField(choices=PICKS)
    # pick = forms.ChoiceField(choices=PICKS, widget=forms.RadioSelect())
    
    class Meta:
        model = Comment
        fields = ('pick', 'content',)

03_DB/99_django_either_pjt/eithers/views.py
from django.db.models import Q, Count
from django.shortcuts import render, redirect
from .models import Question
from .forms import QuestionForm, CommentForm

# Create your views here.
def index(request):
    questions = Question.objects.order_by('-pk')
    context = {
        'questions': questions,
    }
    return render(request, 'eithers/index.html', context)


def create(request):
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.save()
            return redirect('eithers:detail', question.pk)
    else:
        question_form = QuestionForm()
    context = {
        'question_form': question_form,
    }
    return render(request, 'eithers/create.html', context)


def detail(request, question_pk):
    # 1. annotate를 사용하지 않는 방법
    # question = Question.objects.get(pk=question_pk)

    # count_a = len(question.comment_set.filter(pick=0))
    # count_b = len(question.comment_set.filter(pick=1))
    # total_count = count_a + count_b

    if total_count == 0:
        a_per = 0
        b_per = 0
    else:
        a_per = round(count_a / total_count * 100, 2)
        b_per = round(count_b / total_count * 100, 2)

    ###################################################

    # 2. annotate를 사용한 방법
    
    # Filtering on annotations
    count_a = Count('comment', filter=Q(comment__pick=0))
    # count_a=Count('comment', filter=Q(comment__pick=False))
    count_b = Count('comment', filter=Q(comment__pick=1))
    total_count = Count('comment')
    
    question = Question.objects.annotate(
                                    total_count=total_count,
                                    count_a=count_a,
                                    count_b=count_b
                                ).get(pk=question_pk)

    a_per = round(question.count_a / question.total_count * 100, 2) if question.total_count else 0
    b_per = round(question.count_b / question.total_count * 100, 2) if question.total_count else 0
    
    # 1 & 2 공통 사항
    comment_form = CommentForm()    
    comments = question.comment_set.order_by('-pk')

    context = {
        'question': question,
        'comments': comments,
        'comment_form': comment_form,
        'a_per': a_per,
        'b_per': b_per,
    }
    return render(request, 'eithers/detail.html', context)


def comments_create(request, question_pk):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.question_id = question_pk
        comment.save()
    return redirect('eithers:detail', question_pk)


def random(request):
    # 1. random 모듈을 사용하는 방법
    import random

    pk_list = []
    for value in Question.objects.values('pk'):
        pk_list.append(value['pk'])
    question = Question.objects.get(pk=random.choice(pk_list))

    # 2. random 모듈을 사용하지 않는 방법
    # question = Question.objects.order_by('?')[:1]

    count_a = len(question.comment_set.filter(pick=0))
    count_b = len(question.comment_set.filter(pick=1))
    total_count = count_a + count_b

    comment_form = CommentForm()
    comments = question.comment_set.order_by('-pk')

    if total_count == 0:
        a_per = 0
        b_per = 0
    else:
        a_per = round(count_a / total_count * 100, 2)
        b_per = round(count_b / total_count * 100, 2)
    
    context = {
        'question': question, 
        'comments': comments,
        'comment_form': comment_form,
        'a_per': a_per, 
        'b_per': b_per,
    }

    return render(request, 'eithers/detail.html', context)

03_DB/99_django_either_pjt/eithers/templates/eithers/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form question_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>
{% endblock content %}

03_DB/99_django_either_pjt/eithers/templates/eithers/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>DETAIL</h1>
  <a href="{% url 'eithers:index' %}">BACK</a>

  <hr>

  <div class="text-center display-1 mb-3">{{ question.title }}</div>
  <div class="d-flex justify-content-between">
    <h3 class="text-primary">{{ question.issue_a }}</h3>
    <h3 class="text-danger">{{ question.issue_b }}</h3>
  </div>

  <div class="progress" style="height: 30px;">
    <div class="progress-bar progress-bar-striped bg-primary" style="width: {{ a_per }}%">{{ a_per }} %</div>
    <div class="progress-bar progress-bar-striped bg-danger" style="width: {{ b_per }}%">{{ b_per }} %</div>
  </div>

  <hr>

  <h3>댓글 작성</h3>
  <form action="{% url 'eithers:comments_create' question.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button type="submit" class="btn btn-warning btn-lg btn-block">작성</button>
  </form>

  <hr>

  <h3>댓글 목록</h3>
  {% for comment in comments %}
    {% if comment.pick %}
      <div class="alert alert-danger" role="alert">{{ comment.content }}</div>
    {% else %}
      <div class="alert alert-primary" role="alert">{{ comment.content }}</div>
    {% endif %}
    <hr>
  {% empty %}
    <h4>아직 의견이 없습니다... </h4>
  {% endfor %}
{% endblock content %}

03_DB/99_django_either_pjt/eithers/templates/eithers/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="">Either Game</h1>
  <a href="{% url 'eithers:create' %}" class="btn btn-primary">New Question</a>
  <a href="{% url 'eithers:random' %}" class="btn btn-danger">Random Question</a>
  <hr>
  {% for question in questions %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ question.title }}</h5>
        <a href="{% url 'eithers:detail' question.pk %}" class="btn btn-warning">play</a>
      </div>
    </div>
  {% endfor %}
{% endblock content %}

03_DB/99_django_either_pjt/templates/base.html
{% load bootstrap5 %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Either Project</title>
  </head>
  <body>
    <div class="container my-5">
      {% block content %}
      {% endblock %}
    </div>
    {% bootstrap_javascript %}
</body>
</html>